[package]
name = "ssd1306-raspi-examples"
version = "0.1.0"
authors = ["Ferdia McKeogh <ferdia@mckeogh.tech>"]

[dependencies]
linux-embedded-hal = "0.3.1"
embedded-graphics = "0.7.1"
machine-ip = "0.2.1"
ssd1306 = "0.7.0"
